using Mitsui.Sale.Domain.Model.Enumerations;
using Mitsui.Sale.Domain.Model.ValueObjects;

namespace Mitsui.Sale.Domain.Model.Entities;

/// <summary>
/// Bill aggregate root.
/// </summary>
public class Bill
{
    /// <summary>Primary key autogenerated.</summary>
    public int BillNumber { get; set; }

    /// <summary>Customer name.</summary>
    public string Customer { get; set; } = string.Empty;

    /// <summary>Service identifier.</summary>
    public EService ServiceId { get; set; }

    /// <summary>Vehicle plate.</summary>
    public string? Plate { get; set; }

    /// <summary>Emission date.</summary>
    public DateTime Emission { get; set; }

    /// <summary>Invoice value object.</summary>
    public Invoice Invoice { get; set; } = new();

    /// <summary>Bill amount.</summary>
    public double Amount { get; set; }

    /// <summary>Record creation date.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>Date of last update.</summary>
    public DateTime UpdatedAt { get; set; }
}
